Created instructions component for home page
HackYourFuture-CPH/rate-my-cv pull request #106
Opened 2021-02-02 20:25 UTC by Kiran-Serolla

# This is the instructions component for home page

Please provide a short summary explaining what this PR is about.

Fixes # (101)

# How to test?

This can be tested in storybook under InstructionsComponent

![Screenshot (19)](https://user-images.githubusercontent.com/62523704/106658035-10bc9f80-659d-11eb-86d9-22fa1296013c.png)
# Checklist
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] This PR is ready to be merged and not breaking any other functionality

2021-02-04 10:10 UTC, h09shais commented
[Build is failing!](https://github.com/HackYourFuture-CPH/rate-my-cv/pull/106/checks?check_run_id=1817607950)

2021-02-05 12:13 UTC, arya56 commented on src/client/components/InstructionsComponent/InstructionsComponent.css
> +
There need to be some white space above h2.. maybe with padding top.

2021-02-05 12:13 UTC, arya56 commented on src/client/components/InstructionsComponent/InstructionsComponent.css
> +
We might have some bottom padding to add more white spaces like the design we have in the figma.

2021-02-05 13:01 UTC, pdsorensen requested changes
Looks good. Check if any of the suggestions can be made and then add me as a reviewer. 

Also, be very careful of using generic words as css classes. A word like `image` could end up creating css conflicts which can be hard to debug.

2021-02-09 10:21 UTC, pdsorensen requested changes

2021-02-09 10:21 UTC, pdsorensen commented on src/client/components/InstructionsComponent/InstructionsComponent.css
> +h2 {
No global styling please.

2021-02-09 10:45 UTC, pdsorensen approved these changes

2021-02-09 10:45 UTC, merged