Update package.json & package-lock
HackYourFuture-CPH/rate-my-cv pull request #146
Opened 2021-02-10 15:05 UTC by arya56

# Description
remove the problem of adding image in components
Please provide a short summary explaining what this PR is about.
Regarding the conversation with @zkwsk  guided to update package-lock as well
Fixes # (issue)
#141
# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-02-10 19:57 UTC, pdsorensen requested changes
Let's not check in the package-lock file.

2021-02-10 21:01 UTC, arya56 commented
So just remove package-lock.json from this ? @pdsorensen

2021-02-12 05:43 UTC, arya56 commented
Done

2021-02-12 08:40 UTC, pdsorensen approved these changes

2021-02-12 10:13 UTC, merged