Added review post for CV review
HackYourFuture-CPH/rate-my-cv pull request #162
Opened 2021-02-12 21:31 UTC by Kiran-Serolla

# This PR creates a Review post component for CV review

Please provide a short summary explaining what this PR is about.

Fixes # 89

# How to test?
It can be tested in storybook
![Screenshot (20)](https://user-images.githubusercontent.com/62523704/107824591-027f3800-6d82-11eb-9e45-a718e2917649.png)

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2021-02-13 15:29 UTC, zuhairtaha requested changes

2021-02-14 10:38 UTC, Kiran-Serolla commented on src/client/components/ReviewPost/ReviewPost.styles.css
> +}
Done!

2021-02-17 12:11 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.styles.css
> +  display: flex;
Maybe grid works better?
When I started working on the component I made similar to this one, I also used flex but I think in the end grid made it easier. Up to you ofc.

2021-02-17 12:11 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.styles.css
> +  height: 100px;
Just choose one: either width or height, don't change both because then the image gets squished 
```suggestion
```

2021-02-17 12:11 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +import profileImage from '../../assets/images/portraits/man2.jpg';
```suggestion
import profileImage from '../../assets/images/portraits/unknown-black.png';
```

2021-02-17 12:11 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.stories.js
> +    date={new Date()}
It will be good to add an example where you pass a profile image

2021-02-19 20:41 UTC, Kiran-Serolla commented on src/client/components/ReviewPost/ReviewPost.styles.css
> +.profile-image img {
I tried  using the same class name but it didnt work . I also tried applying same styling as your component but it still dosen't work

2021-02-21 14:34 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +      <span className="description">{description}</span>
Everything seems good, I just notice that the description uses this color: #9A9A9A, you might need a different class name, as we have other components using that class

2021-02-21 16:49 UTC, valmdz reviewed
Just made a suggestion for the naming of some variables to avoid conflicts in other components

2021-02-21 16:49 UTC, valmdz approved these changes

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +export const ReviewPost = ({ name, description, date, profileImageUrl }) => {
```suggestion
export const ReviewPost = ({ fullName, review, createdDate, profileImageUrl }) => {
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +        <span className="name">{name} </span>
```suggestion
        <span className="name">{fullName} </span>
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +        <span className="date-time">{date.toLocaleString()}</span>
```suggestion
        <span className="date-time">{createdDate.toLocaleString()}</span>
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +      <span className="review-text">{description}</span>
```suggestion
      <span className="review-text">{review}</span>
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +  name: PropTypes.string,
```suggestion
  fullName: PropTypes.string,
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +  description: PropTypes.string,
```suggestion
  review: PropTypes.string,
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +  date: PropTypes.instanceOf(Date),
```suggestion
  createdDate: PropTypes.instanceOf(Date),
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +  name: '',
```suggestion
  fullName: '',
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +  description: '',
```suggestion
  review: '',
```

2021-02-21 17:24 UTC, valmdz commented on src/client/components/ReviewPost/ReviewPost.js
> +  date: '',
```suggestion
  createdDate: '',
```

2021-02-22 18:13 UTC, ember-b-Moss commented
hey @pdsorensen ,

2021-02-22 19:45 UTC, merged