User sign-out
HackYourFuture-CPH/rate-my-cv pull request #205
Opened 2021-02-24 09:50 UTC by arya56

# Description

Please provide a short summary explaining what this PR is about.

Fixes # (issue)
204
# How to test?
scroll over the user icon on header, click on sign out link in the tool-tip box
Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-02-24 15:19 UTC, pdsorensen requested changes

2021-02-24 18:13 UTC, arya56 commented on src/client/components/Navigation/Header.js
> +  username: PropTypes.string,
@pdsorensen I have done that in the Profile branch it's hasn't been merged yet, since this is only related to sign out. :smiley:

2021-02-24 19:03 UTC, pdsorensen commented on src/client/components/Navigation/Header.js
> +  username: PropTypes.string,
It is: https://github.com/HackYourFuture-CPH/rate-my-cv/blob/develop/src/client/hooks/useAuthentication.js#L4

2021-02-24 20:34 UTC, arya56 commented on src/client/components/Navigation/Header.js
> +  username: PropTypes.string,
@pdsorensen Done :bicyclist:

2021-02-25 08:39 UTC, pdsorensen approved these changes

2021-02-25 08:39 UTC, merged