34 uploading file
HackYourFuture-CPH/rate-my-cv pull request #54
Opened 2021-01-24 01:15 UTC by hamedveloper

# Description

This story is about a function that when invoked with a file as a argument will upload the file. It returns a url for accessing that file! 

Fixes # (issue)

# How to test?

For making a test you should first creat a project in firebase and a database in there as well. You should change the firebase Config here in the code based on the configure parameters in firebase. Afterward give a file to the function and in the result you can give a Url of that updated file. 
 
# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2021-01-24 14:50 UTC, benna100 requested changes
the changes in package.json is not part of the story

2021-01-24 14:50 UTC, benna100 commented on src/client/hooks/fileUploader.js
> +      console.log(snapShot);
remove the console.log

2021-01-24 14:50 UTC, benna100 commented on src/client/hooks/fileUploader.js
> +  const uploadTask = storage.ref(`/CVs/${cv.name}`).put(cv);
```suggestion
  const uploadTask = storage.ref(`/cvs/${cv.name}`).put(cv);
```

2021-01-28 09:43 UTC, benna100 commented
@hamedveloper are you still working on this?

2021-01-28 09:45 UTC, hamedveloper commented
Yes I am. I just finished with another story and comming back to finish
this one today

On Thu, 28 Jan 2021 at 10.44, benna100 <notifications@github.com> wrote:

> @hamedveloper <https://github.com/hamedveloper> are you still working on
> this?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/HackYourFuture-CPH/rate-my-cv/pull/54#issuecomment-768930141>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANC53NCYGOTROMX2EKISP73S4EWWHANCNFSM4WQDZTKQ>
> .
>

2021-01-28 23:52 UTC, hamedveloper commented
@benna100 Please check. I have done it in another way. 


https://user-images.githubusercontent.com/54910388/106212978-09c41480-61cc-11eb-931a-5f5471ae53cb.mp4

2021-01-31 10:05 UTC, benna100 submitted a review, later dismissed
Hamed you need to clean this PR up. There are lots and lots of changes not related to your story

2021-01-31 10:32 UTC, hamedveloper commented
Can you let me know how I can clean up changes? It did not let me commit because of formatting and as soon as I made other files format let me to commit. and now I can see I have conflict here!!

2021-02-01 14:35 UTC, pdsorensen commented
@hamedveloper, if you go into the "files changed" section of your PR, you can see alot of changes has been made to files that it shouldn't be changed. You also need to merge this branch with the latest changes in develop. 

Cheers,

2021-02-04 12:21 UTC, valmdz commented on src/client/hooks/fileUploader.js
> +          const downloadUrl = await storageRef.getDownloadURL();
```suggestion
          const downloadedUrl = await storageRef.getDownloadURL();
```

2021-02-04 12:21 UTC, valmdz commented on src/client/hooks/fileUploader.js
> +          setUrl(downloadUrl);
```suggestion
          setUrl(downloadedUrl);
```

2021-02-07 21:13 UTC, pdsorensen approved these changes
@hamedveloper this is great! Great video as well, makes it really easy to see what you have done. Great job also trimming the PR down. 💯

2021-02-07 21:14 UTC, merged