PageHeader to Upload CV, issue_41 done
HackYourFuture-CPH/rate-my-cv pull request #74
Opened 2021-01-28 15:53 UTC by CharlesKimMaina

# Description

A search page header is created where you can upload your CV,.,(Nb, currently the button is STATIC, it will fetch CVs later in the project)

Fixes # 41

# How to test?
1. run npm run story and see the component come up as below.
<img width="943" alt="Header4UploadingCV_storybook" src="https://user-images.githubusercontent.com/58881390/106162688-ad8bd100-6188-11eb-9930-570f52aac72a.PNG">

2. You can also test it in localhost npm run dev but u must import PageHeader component in app.js (Client-side), and the component will be like below; both at full screen and at mobile platform;;;
<img width="953" alt="Header4UploadingCV" src="https://user-images.githubusercontent.com/58881390/106162953-efb51280-6188-11eb-8ab3-71de2d457f64.PNG">
<img width="178" alt="Header4UploadingCV_mobile" src="https://user-images.githubusercontent.com/58881390/106162974-f5aaf380-6188-11eb-98e4-94a106274cf6.PNG">

# Checklist

- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] This PR is ready to be merged and not breaking any other functionality

2021-01-29 10:01 UTC, kamalrsa commented
looks nice !!

2021-01-31 10:24 UTC, benna100 requested changes
Small changes, otherwise looks good!

2021-01-31 10:24 UTC, benna100 commented on src/client/components/PageHeaderComponent/PageHeader.js
> +          <div className = "cv-btn">
```suggestion
          <div className = "cv-button">
```

2021-01-31 10:24 UTC, benna100 commented on src/client/components/PageHeaderComponent/PageHeader.js
> +            <Button buttonName={'Upload New Cv'} backgroundColor = {("backgroundColor", "black")} />
Fix the error here!

2021-01-31 10:24 UTC, benna100 commented on src/client/components/PageHeaderComponent/PageHeader.styles.css
> +@media(max-width: 450px){
Great with the responsive design

2021-01-31 14:15 UTC, benna100 approved these changes
Looks good! Remember indentation. Really remember it. Install prettier so that it helps you and you dont even need to think about it!

2021-01-31 14:15 UTC, benna100 commented on src/client/components/PageHeaderComponent/PageHeader.js
> +        <Search />
Indentation. No need to fix it. BUT this should not be something i should need to comment at this stage! Use prettier that is what it is there for. Not indenting your code is a big red flag in my opinion. So remember that!

2021-01-31 14:15 UTC, benna100 commented on src/client/components/PageHeaderComponent/PageHeader.js
> +            <Button buttonName="Upload New Cv" style = {{ backgroundColor: 'black', color: "white" }}/>
```suggestion
            <Button buttonName="Upload New Cv" style={{ backgroundColor: 'black', color: "white" }}/>
```

2021-01-31 14:15 UTC, benna100 commented on src/client/components/PageHeaderComponent/PageHeader.js
> +      <div className="search-button">
This is but a button but a div. I will accept it. But remember these things

2021-01-31 14:15 UTC, merged