Users patch branch 0.6
HackYourFuture-CPH/rate-my-cv pull request #81
Opened 2021-01-29 20:59 UTC by DiegoRuiz454

# **Description**

PATCH api/users/{id} query parameter implemented. users.controllers.js and users.router.js. the user can edit and update: full_name, position, linkedin,github, website, profile_image_url. What if the id does not exists? the following message will appear: `the cv with the id number :'${req.params.id}' doesn't exist in our database. Please check again!`

Fixes # (29)

# **How to test?**

type in the terminal npm run dev. after test it with POSTMAN select PATCH while using the endpoint
http://localhost:5000/api/users/{id} after that press send. 

# **Checklist**

- [☑] I have performed a self-review of my own code
- [☑] I have commented my code, particularly in hard-to-understand areas
- [☑] I have made corresponding changes to the documentation
- [☑] This PR is ready to be merged and not breaking any other functionality
![users 1](https://user-images.githubusercontent.com/66638147/106326669-24a29180-627d-11eb-8594-76a5e38437ee.PNG)
![users does not exist](https://user-images.githubusercontent.com/66638147/106326714-35530780-627d-11eb-8979-24444e97b089.PNG)

2021-01-29 22:22 UTC, pdsorensen commented
Hi @DiegoRuiz454 , it looks good! Can i have you look at files changed, and go each of the github warning/errors related to your files? 

Also, i don't understand why so many deletions is happening in the swagger file. I think this is unintended? :)

2021-01-31 12:54 UTC, bytewiz requested changes
You renamed the controller: `users.controller.js` to  `users.controllers.js`
Please avoid that so we keep it consistent and avoid conflicts it should be named.

`users.controller.js`

2021-01-31 12:54 UTC, bytewiz commented on src/server/api/routes/users.router.js
> + * /cvs/{ID}:
```suggestion
 * /users/{ID}:
```

2021-01-31 12:54 UTC, bytewiz commented on src/server/api/routes/users.router.js
> + *      Will create a new user.
Will it create a new user or update the user?

2021-02-02 15:09 UTC, closed without merging